# Generated by Django 3.2.6 on 2021-11-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pieimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PieImage',
        ),
    ]
