# Generated by Django 3.2.6 on 2021-11-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
